---
- name: Lookup currently installed ruby revision
  shell:         "cat {{ruby_location}}/share/.ruby-revision || echo '' "
  ignore_errors: yes
  register: found_current_ruby_revision

- include: install.yml
  when: found_current_ruby_revision.stdout != ruby_revision
